mock:
  server:
    address: test
  image:
    catalog:
      url: https://test:9443/imagecatalog

integrationtest:
    testsuite:
      threadPoolSize: 1
      pollingInterval: 1000
    defaultBlueprintName: hdp-small-default
    outputdir: /it
    command: suites
    cleanup:
      cleanupBeforeStart: true
